#version 440

layout (set = 1, binding = 0, rgba16f) uniform coherent image2D bufferA;
layout (set = 1, binding = 1, rgba16f) uniform coherent image2D bufferB;

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

const float PI = 3.14159265359;

void main()
{
    vec4 val = imageLoad(bufferA, ivec2(gl_GlobalInvocationID.xy));
    imageStore(bufferB, ivec2(gl_GlobalInvocationID.xy), vec4(val.xy*2-1, 0, 1));
}
